site_name: Citrix NetScaler SD-WAN 11.0 NITRO API Documentation
site_description: Citrix NetScaler SD-WAN 11.0 NITRO API Documentation
site_title: Developer Docs
site_url: https://developer-docs.citrix.com/

# Copyright
copyright: '&copy; 1999-2020 Citrix Systems, Inc. All rights reserved. '

# Feedback

issues_uri: https://github.com/citrix/netscaler-sdwan-nitro-api-reference/issues/new
assignees_uri:
  - ajitchelat
labels_uri:
  - documentation

extra_css:
  - 'assets/stylesheets/extra.css'
  - https://use.fontawesome.com/releases/v5.12.1/css/all.css

# Configuration
theme:
  name: null
  custom_dir: devdocs-theme
  
  # 404 page
  static_templates:
    - 404.html
  
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  
  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - tabs: false
  palette:
    primary: teal
    accent: teal
  font: false
  favicon: https://docs.citrix.com/assets/images/favicon.ico
  logo: https://developer-docs.citrix.com/_static/logo.svg
  icon: fontawesome

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCiOupk9QF6jdk3EDKTHDykA
    - icon: fontawesome/brands/github-alt
      link: https://github.com/citrix
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/citrixdeveloper
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/citrix/

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

plugins:
  - search:
      separator: '[\s\-\.]+'

# Page tree
nav:
 - Getting Started Guide: index.md
 - Configuration:
   - appliance_certificate: config/appliance_certificate.md
   - change_management: config/change_management.md
   - config_package_export: config/config_package_export.md
   - config_package_import: config/config_package_import.md
   - config_package_save_as: config/config_package_save_as.md
   - config_packages: config/config_packages.md
   - dynamic_route: config/dynamic_route.md
   - enable_disable_path: config/enable_disable_path.md
   - ethernet_adapters: config/ethernet_adapters.md
   - file_upload_to_inbox: config/file_upload_to_inbox.md
   - get_package_file: config/get_package_file.md
   - license_info: config/license_info.md
   - local_change_management: config/local_change_management.md
   - local_license: config/local_license.md
   - local_users: config/local_users.md
   - login: config/login.md
   - management_ip: config/management_ip.md
   - ntp_servers: config/ntp_servers.md
   - os_partition: config/os_partition.md
   - radius_settings: config/radius_settings.md
   - remote_license: config/remote_license.md
   - saas_service: config/saas_service.md
   - service: config/service.md
   - sites_cm_info: config/sites_cm_info.md
   - system_options: config/system_options.md
   - tacacs_settings: config/tacacs_settings.md
   - update_schedule: config/update_schedule.md
   - wanlink: config/wanlink.md
 - Monitoring:
   - access_interfaces: monitor/access_interfaces.md
   - appliance_ha_status: monitor/appliance_ha_status.md
   - application_routes: monitor/application_routes.md
   - application_rules: monitor/application_rules.md
   - applications: monitor/applications.md
   - arp_table: monitor/arp_table.md
   - class_cols: monitor/class_cols.md
   - classes: monitor/classes.md
   - dns_proxy_stats: monitor/dns_proxy_stats.md
   - dns_transparent_forwarder_stats: monitor/dns_transparent_forwarder_stats.md
   - dynamic_routing_protocol_stats: monitor/dynamic_routing_protocol_stats.md
   - ethernet_mac_learning_stats: monitor/ethernet_mac_learning_stats.md
   - ethernet_stats: monitor/ethernet_stats.md
   - firewall_connection_stats: monitor/firewall_connection_stats.md
   - firewall_filter_stats: monitor/firewall_filter_stats.md
   - firewall_nat_stats: monitor/firewall_nat_stats.md
   - flows: monitor/flows.md
   - gre_tunnel_stats: monitor/gre_tunnel_stats.md
   - ilbflows: monitor/ilbflows.md
   - intranet: monitor/intranet.md
   - ipsec_tunnels_stats: monitor/ipsec_tunnels_stats.md
   - mpls_queues: monitor/mpls_queues.md
   - multicast_groups: monitor/multicast_groups.md
   - observed_protocols: monitor/observed_protocols.md
   - paths: monitor/paths.md
   - paths_detailed: monitor/paths_detailed.md
   - pppoe_status: monitor/pppoe_status.md
   - routes_stats: monitor/routes_stats.md
   - rule_group_stats: monitor/rule_group_stats.md
   - rules: monitor/rules.md
   - sites_stats: monitor/sites_stats.md
   - tcptermflows: monitor/tcptermflows.md
   - virtual_path_services: monitor/virtual_path_services.md
   - virtual_paths: monitor/virtual_paths.md
   - wan_link_usage_stats: monitor/wan_link_usage_stats.md
   - wanlinkstat: monitor/wanlinkstat.md
 - Configuration Editor:
   - app_qoe: config_editor/app_qoe.md
   - app_qoe_profile: config_editor/app_qoe_profile.md
   - application_objects: config_editor/application_objects.md
   - application_qos: config_editor/application_qos.md
   - application_route: config_editor/application_route.md
   - autopath_groups: config_editor/autopath_groups.md
   - bgp_export_filters: config_editor/bgp_export_filters.md
   - bgp_import_filters: config_editor/bgp_import_filters.md
   - bgp_neighbor: config_editor/bgp_neighbor.md
   - bgp_policy: config_editor/bgp_policy.md
   - bgp_properties: config_editor/bgp_properties.md
   - centralized_licensing_global: config_editor/centralized_licensing_global.md
   - centralized_licensing_site: config_editor/centralized_licensing_site.md
   - community_string_list: config_editor/community_string_list.md
   - config_editor_classes: config_editor/config_editor_classes.md
   - config_editor_rules: config_editor/config_editor_rules.md
   - connections_application_settings: config_editor/connections_application_settings.md
   - connections_office_365_breakout_policy: config_editor/connections_office_365_breakout_policy.md
   - dns_proxy: config_editor/dns_proxy.md
   - dns_service: config_editor/dns_service.md
   - dns_transparent_forwarder: config_editor/dns_transparent_forwarder.md
   - domain_name_based_applications: config_editor/domain_name_based_applications.md
   - dynamic_virtual_path_default_set: config_editor/dynamic_virtual_path_default_set.md
   - dynamic_virtual_path_default_set_advanced_settings: config_editor/dynamic_virtual_path_default_set_advanced_settings.md
   - dynamic_virtual_path_default_set_application_qos: config_editor/dynamic_virtual_path_default_set_application_qos.md
   - dynamic_virtual_path_default_set_bulk_classes: config_editor/dynamic_virtual_path_default_set_bulk_classes.md
   - dynamic_virtual_path_default_set_interactive_classes: config_editor/dynamic_virtual_path_default_set_interactive_classes.md
   - dynamic_virtual_path_default_set_ipsec_properties: config_editor/dynamic_virtual_path_default_set_ipsec_properties.md
   - dynamic_virtual_path_default_set_realtime_classes: config_editor/dynamic_virtual_path_default_set_realtime_classes.md
   - dynamic_virtual_path_default_set_rules: config_editor/dynamic_virtual_path_default_set_rules.md
   - dynamic_virtual_path_provisioning: config_editor/dynamic_virtual_path_provisioning.md
   - dynamic_virtual_paths: config_editor/dynamic_virtual_paths.md
   - external_tracker_delete: config_editor/external_tracker_delete.md
   - firewall: config_editor/firewall.md
   - firewall_destination_policy_delete: config_editor/firewall_destination_policy_delete.md
   - firewall_dynamic_nat_policy_delete: config_editor/firewall_dynamic_nat_policy_delete.md
   - firewall_local_policy_delete: config_editor/firewall_local_policy_delete.md
   - firewall_policy_template: config_editor/firewall_policy_template.md
   - firewall_policy_template_delete: config_editor/firewall_policy_template_delete.md
   - firewall_settings_delete: config_editor/firewall_settings_delete.md
   - firewall_static_nat_policy_delete: config_editor/firewall_static_nat_policy_delete.md
   - firewall_zones: config_editor/firewall_zones.md
   - global_application_settings: config_editor/global_application_settings.md
   - global_network_settings: config_editor/global_network_settings.md
   - ha_appliance: config_editor/ha_appliance.md
   - ha_interface_group_delete: config_editor/ha_interface_group_delete.md
   - ha_service: config_editor/ha_service.md
   - interface_groups: config_editor/interface_groups.md
   - internet_service: config_editor/internet_service.md
   - internet_service_rules: config_editor/internet_service_rules.md
   - internet_service_wan_links: config_editor/internet_service_wan_links.md
   - intranet_service: config_editor/intranet_service.md
   - intranet_service_rules: config_editor/intranet_service_rules.md
   - intranet_services_wan_links: config_editor/intranet_services_wan_links.md
   - ipsec_tunnel: config_editor/ipsec_tunnel.md
   - mpls_queue: config_editor/mpls_queue.md
   - office_365_breakout_policy: config_editor/office_365_breakout_policy.md
   - ospf_area: config_editor/ospf_area.md
   - ospf_area_virtual_interface_delete: config_editor/ospf_area_virtual_interface_delete.md
   - ospf_export_filters: config_editor/ospf_export_filters.md
   - ospf_import_filters: config_editor/ospf_import_filters.md
   - ospf_properties: config_editor/ospf_properties.md
   - panw_branch_maps: config_editor/panw_branch_maps.md
   - path: config_editor/path.md
   - provisioning_groups: config_editor/provisioning_groups.md
   - proxy_auto_config_file_settings: config_editor/proxy_auto_config_file_settings.md
   - region: config_editor/region.md
   - routes: config_editor/routes.md
   - routing_domain: config_editor/routing_domain.md
   - rule_groups: config_editor/rule_groups.md
   - saas_gateway_application_object_delete: config_editor/saas_gateway_application_object_delete.md
   - saas_gateway_service: config_editor/saas_gateway_service.md
   - saas_gateway_wan_link_usage_delete: config_editor/saas_gateway_wan_link_usage_delete.md
   - service_provider: config_editor/service_provider.md
   - service_provisioning: config_editor/service_provisioning.md
   - site_dns_service: config_editor/site_dns_service.md
   - site_proxy_auto_config_file_settings: config_editor/site_proxy_auto_config_file_settings.md
   - site_routing_domain: config_editor/site_routing_domain.md
   - sites: config_editor/sites.md
   - virtual_ip_addresses: config_editor/virtual_ip_addresses.md
   - virtual_path_default_set: config_editor/virtual_path_default_set.md
   - virtual_path_default_set_advanced_settings: config_editor/virtual_path_default_set_advanced_settings.md
   - virtual_path_default_set_application_qos: config_editor/virtual_path_default_set_application_qos.md
   - virtual_path_default_set_bulk_classes: config_editor/virtual_path_default_set_bulk_classes.md
   - virtual_path_default_set_interactive_classes: config_editor/virtual_path_default_set_interactive_classes.md
   - virtual_path_default_set_ipsec_properties: config_editor/virtual_path_default_set_ipsec_properties.md
   - virtual_path_default_set_realtime_classes: config_editor/virtual_path_default_set_realtime_classes.md
   - virtual_path_default_set_rules: config_editor/virtual_path_default_set_rules.md
   - virtual_path_wan_link_mpls_usage_delete: config_editor/virtual_path_wan_link_mpls_usage_delete.md
   - virtual_path_wan_links: config_editor/virtual_path_wan_links.md
   - virtualpaths: config_editor/virtualpaths.md
   - wan_branch_maps: config_editor/wan_branch_maps.md
   - wan_links: config_editor/wan_links.md
   - wan_optimization_application_classifier: config_editor/wan_optimization_application_classifier.md
   - wan_optimization_application_classifier_application_group: config_editor/wan_optimization_application_classifier_application_group.md
   - wan_optimization_features: config_editor/wan_optimization_features.md
   - wan_optimization_service_classes: config_editor/wan_optimization_service_classes.md
   - wan_optimization_service_classes_filter_rule_delete: config_editor/wan_optimization_service_classes_filter_rule_delete.md
   - wan_optimization_tuning_settings: config_editor/wan_optimization_tuning_settings.md
   - wan_to_wan_forwarding: config_editor/wan_to_wan_forwarding.md
   - zen_branch_maps: config_editor/zen_branch_maps.md
 - Diagnostics:
   - packet_capture: diag/packet_capture.md
 - Download:
   - appliance_certificate_download: download/appliance_certificate_download.md
   - pcap_download: download/pcap_download.md
 - Mobile Broadband:
   - apn_settings: mobile_broadband/apn_settings.md
   - device: mobile_broadband/device.md
   - firmware: mobile_broadband/firmware.md
   - mb_summary: mobile_broadband/mb_summary.md
   - modem: mobile_broadband/modem.md
   - sdwc_mb_summary: mobile_broadband/sdwc_mb_summary.md
   - sim: mobile_broadband/sim.md
   - sim_pin_operations: mobile_broadband/sim_pin_operations.md
   - sim_pin_summary: mobile_broadband/sim_pin_summary.md
   - upload_firmware: mobile_broadband/upload_firmware.md
 
